version: '3.0'

services:
  # ==== ---------------------------------------------------------------------------------------------------------------
  # MARK: Frontend (8000 - 8009)
  frontend:
    build:
      context: services/frontend
    entrypoint: ./Serve --host 0.0.0.0 --tracing.jaeger-host jaeger --tracing.zipkin-collector-port 9411
    ports:
      - 8000:8080
    depends_on:
      - jaeger
      - prometheus
    networks:
      - metrics
      - tracing

  # ==== ---------------------------------------------------------------------------------------------------------------
  # MARK: Jager (9000 - 9009)
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 9000:16686
    networks:
      - metrics
      - tracing
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      ADMIN_HTTP_PORT: 9002

  # ==== ---------------------------------------------------------------------------------------------------------------
  # MARK: Prometheus (9010 - 9019)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9010:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - metrics

volumes:
  prometheus_data: {}

networks:
  tracing:
  metrics:
