scrape_configs:
  - job_name: 'frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['frontend:8001']

  - job_name: 'customer'
    scrape_interval: 5s
    static_configs:
      - targets: ['customer:8011']

  - job_name: 'jaeger'
    scrape_interval: 5s
    static_configs:
      - targets: ['jaeger:9002']
